### ISSUE TITLE
Zooming problem.

### ISSUE THREAD

**Issue by garawaa** [yourealwaysbe/forkyz#24]
There are zooming or scrolling works so strange. Please correct it. Thank you.

**Comment by yourealwaysbe** [comment]
Thanks for the report. From a quick play i think there are three areas that need work:

1. board snaps to bottom-left of screen after zooming out,
2. zoom actions are interpreted as long-presses on board clues (opening the notes page),
3. when scrolling the board sticks to the edges of the screen; this is intentional but a bit too aggressive.

Let me know if these are the issues you're seeing.

**Comment by yourealwaysbe** [comment]
There is a test fix to this on the meta-cache branch. I will merge it in a week to give some time for me to spot bugs with the work in that branch. Then i'll release it to f-droid.
