### ISSUE TITLE
Circles in boxes

### ISSUE THREAD

**Issue by rodan123** [yourealwaysbe/forkyz#29]
I do the LA times crosswords that frequently feature circled letters in the puzzle. Shortyz would display the circles, Forkyz doesn't. Any chance of implementing this feature?

**Comment by yourealwaysbe** [comment]
Ah, dang, then i broke it somewhere along the line. Do you have an example LA Times puzzle i can use to test?

**Comment by yourealwaysbe** [comment]
Ok, found one -- Aug 4th, confirmed the circles aren't showing.

**Comment by rodan123** [comment]
Great. You're much faster than me.
Thanks for looking at this and for keeping the program up to date.

**Comment by yourealwaysbe** [comment]
This looks like it's because i switched the data source from Arkadium Hosted back to Uclick. If I try [the supposed Arkadium Hosted URL for 4 Aug 2021](http://cdn.games.arkadiumhosted.com/latimes/assets/DailyCrossword/la210804.xml) it returns data for the 4 Aug 2019 crossword. Uclick uses a different data format, but [returns the right puzzle](https://picayune.uclick.com/comics/tmcal/data/tmcal210804-data.xml). However, the Uclick data format seems to contain no trace of the circles.

The LA Times website gets the data from a different URL from [Amuse Labs](https://cdn4.amuselabs.com/lat/crossword?id=tca210804&set=latimes&embed=1&picker=date-picker&heightReduction=30&style=1&src=https%3A%2F%2Fwww.latimes.com%2Fgames%2Fdaily-crossword&pickerToken=eyJ1aWQiOiIxYjE4NDEyMC0wMjJjLTQ5NGItOTZkMC1lYTRmNWE4YjY4ZWEiLCJ1cGRhdGVMb2FkVGFibGUiOmZhbHNlLCJ0aW1lc3RhbXAiOjE2Mjg3MTE5OTgzOTR9). However, naive use of this URL gets a blank response outside of a browser, and a fully formed HTML page inside.

So it looks like fixing this bug means figuring out if Uclick hides the circles somewhere in its XML, or if there's a way of getting the Amuse Labs data in a useful format.

**Comment by rodan123** [comment]
Ah, the Uclick XML is pretty straightforward, nothing looks cryptic.
Scraping the Amuse Labs page appears like it might be possible, 
[https://github.com/thisisparker/xword-dl](https://github.com/thisisparker/xword-dl)
But haven't tried the program and it would probably be too much trouble to integrate.

Thanks for the quick response.

**Comment by yourealwaysbe** [comment]
Thanks -- looks like the puzzle JSON is base64 encoded in the window.rawc property. This decodes to a JSON format i don't recognise, but it's not a lot of xword-dl code to get the required info out. It could be done something like [GuardianDailyCrypticDownloader.java](https://github.com/yourealwaysbe/forkyz/blob/master/app/src/main/java/app/crossword/yourealwaysbe/net/GuardianDailyCrypticDownloader.java) which has a similar HTML scraping / JSON handling thing to do. The new class would then need an entry in [Downloaders.java]( https://github.com/yourealwaysbe/forkyz/blob/master/app/src/main/java/app/crossword/yourealwaysbe/net/Downloaders.java) and [preferences_daily.xml](https://github.com/yourealwaysbe/forkyz/blob/master/app/src/main/res/xml/preferences_daily.xml).

It's a bit of work, so i'm not sure if/when i'll do it. I'm happy to accept pull requests though ;)

In the meantime, as a workaround, you can try using xword-dl to get the crosswords as .puz files, then use the (+) button in Forkyz to import them.

(To be honest, there should really be a GuardianIO.java in the [puzlib/.../io]( https://github.com/yourealwaysbe/forkyz/tree/master/puzlib/src/main/java/app/crossword/yourealwaysbe/io) directory that parses the JSON stream instead of doing it directly in GuardianDailyCrypticDownloader.java, but that's a to do for another day.)

**Comment by yourealwaysbe** [comment]
An Amuse Labs downloader is now implemented on the version10 branch. I think this might be useful for several other puzzle sources that i had retired. I will release version10 in a week or so.
