### ISSUE TITLE
Alternate keyboard

### ISSUE THREAD

**Issue by ieure** [yourealwaysbe/forkyz#30]
First off, thanks for picking up maintenance of Shortyz.

The way I've been using Shortyz for years is to have space toggle across/down, and enter skip to the next clue in the same direction.

Even though Forkyz still has has the "Enter Changes Direction" option, the custom keyboard doesn't have an enter key, and the "Keyboard Style" setting from Shortyz (which would let you select the system keyboard) has been removed.  This makes it impossible to use Forkyz like I used Shortyz.  So even though pretty much everything else is improved, I find it more cumbersome and less enjoyable.

What I'd like is either:

 - The restoration of the ability to use the system (or any other installed) keyboard.
 - An alternate custom keyboard with the arrows removed and an enter key added.

**Comment by yourealwaysbe** [comment]
Thanks. I think this area can be improved.

I removed the native keyboard option after discovering Android keyboards don't really deal in keypresses. Although they work as you'd expect on most systems, you can't and shouldn't rely on it.

One benefit of a custom app keyboard is that you can have any button you want, rather than appropriating unused standard keys for other purposes.

I think it would be reasonable to add buttons on the bottom row for toggling direction and moving to the next clue. I think there's room since the space bar is large but doesn't have the importance it does on a regular keyboard. Would that work for you?

I can have a go next week.
-- 
Sent from my phone: apologies for poor formatting and bizarre typos...

**Comment by ieure** [comment]
> I think it would be reasonable to add buttons on the bottom row for toggling direction and moving to the next clue. I think there's room since the space bar is large but doesn't have the importance it does on a regular keyboard. Would that work for you?

Yes, that would work fine.  I don't care if it's the native keyboard or not, as long as I have some way of skipping to the next clue in the same direction (or first in the opposite direction if I'm at the end of the clues).  The native keyboard was the only way Shortyz could do that.
