### ISSUE TITLE
Next-clue button does not switch to the other direction when reaching the last clue

### ISSUE THREAD

**Issue by cliambrown** [yourealwaysbe/forkyz#48]
Thanks for the recent updates — the app is excellent!

I noticed that the right-chevron button next to the spacebar now follows the same rules as when you type in the last letter of a word (i.e. skipping filled-in boxes), which is great. However, when you get to the last across clue and hit that button, it will take you to the first across clue instead of the first down clue.

I also noticed that the left-chevron button does not obey the same rules, i.e. skipping filled boxes. Is that intentional? I kind of like it that way, but I was curious.

**Comment by yourealwaysbe** [comment]
> when you get to the last across clue and hit that button, it will take you to the first across clue instead of the first down clue.

Thanks. I took a shortcut with that when converting from fixed across/down lists to general lists/zones, then forgot to come back to it. I'll sort it for Version 21.

> I also noticed that the left-chevron button does not obey the same rules, i.e. skipping filled boxes. Is that intentional? I kind of like it that way, but I was curious.

Possibly this is the fix of #44. As far as i can tell, going backwards has never skipped filled boxes. Going forwards originally did in Shortyz, but at some point i broke it.

I generally don't use the navigation buttons much, so happy to receive bug reports since i don't realise easily if i break something..
