### ISSUE TITLE
Disambiguation for order of lights in clue

### ISSUE THREAD

**Issue by pseudomonas** [yourealwaysbe/forkyz#49]
For Guardian crosswords at least, there is a problem where a clue spans multiple lights.

The first light is labelled something like 
 15. TEXT OF CLUE (7,4,4)

subsequent lights (which one must find by looking through lights one by one) are labelled
 5. See 15
 20. See 15

On solving the clue, one cannot tell (absent information from crosses) whether the answers should be entered in the order 15,5,20 or 15,20,5.

I suggest that the solution would be to put the order in the first light:

  15,20,5. TEXT OF CLUE (7,4,4)

(it would also be nice if the anagram/notes tool corresponded to the length of the clue rather than the length of the light; but that might be more work to implement.)

**Comment by yourealwaysbe** [comment]
I've had this on my mind recently too (i'm on No. 28,768) :)

When i wrote the Guardian downloader the backend was using the Across Lite file format, which only supports simple clue numbers and across/down contiguous blocks. Since then i've moved it to IPuz and added support for clues that are all over the grid. (E.g. The Independent No. 11,115 has a bit of this, and the anagram/notes has all the clue cells.)

In principle, Forkyz could handle it like the Guardian web app ([e.g.](https://www.theguardian.com/crosswords/cryptic/28768#28-across)). It's on the list for version 22 :)

**Comment by pseudomonas** [comment]
Thank you! And thanks for all the work you've put into making Forkyz my №1 timesink!

**Comment by yourealwaysbe** [comment]
This should now be working in version22 (on its way to FDroid).
