### ISSUE TITLE
Hamburger Abendblatt download fails

### ISSUE THREAD

**Issue by njmdietrich** [yourealwaysbe/forkyz#71]
The download for Hamburger Abendblatt stopped working a while ago. I think it has worked before on the most recent app version so perhaps the source has changed?

**Comment by yourealwaysbe** [comment]
Thanks for the report. Just spotted this yesterday (https://github.com/yourealwaysbe/forkyz/commit/9224d1ede7b4192a23491ebb0c6da07de7460c86). Turns out the fix was the remove a slash from the end of the URL..

**Comment by njmdietrich** [comment]
Awesome! Thank you for your swift response. Do you have an ETA of the next version including those fixes?

**Comment by yourealwaysbe** [comment]
Hopefully within a couple of weeks (the FDroid release cycle can take a week or so), but there's at least one more thing i wanted to add first.

Here's [an updated version](https://github.com/yourealwaysbe/forkyz/files/11584052/forkyz.apk.zip) to be going on with.  You'll need to uninstall and reinstall because it doesn't have the FDroid signature (which will also reset your settings).

**Comment by njmdietrich** [comment]
thank you very much. I have been using this version for the last day now. I suppose I will leave this issue open until the fix makes it to the next update in case people have the same issue.

**Comment by yourealwaysbe** [comment]
I'll close this now as i'm preparing a release.

Let me know if there are more issues. Note, i'm moving development to [GitLab](https://gitlab.com/Hague/forkyz), so new issues can be posted there. :)
