### ISSUE TITLE
[Feature request] f-droid inclusion

### ISSUE THREAD

**Issue by mooomooo** [yourealwaysbe/forkyz#8]
It would be great if this were included in f-droid:

https://f-droid.org/en/docs/Inclusion_How-To/

**Comment by yourealwaysbe** [comment]
I've thought about adding this to F-Droid, but have always shied away from it. Partly this is because i don't make a great maintainer since it can often be a long time before i get around to addressing issues. I've also enjoyed using this as my own personal playground - happily ditching features if they get in the way of something i want, and not worrying much if i introduce a breaking change or things display badly on other devices.

I won't mind much if someone else adds it though -- then i can still maintain some lack of responsibility for it.

**Comment by yourealwaysbe** [comment]
Change of heart here :) -- Shortyz will no longer work with Android 11, and i've done a bunch of work to convert it, which rolled onto to cleaning up all linting and compiler warnings, etc. Probably a good time to release.
